# File: .github/workflows/repo-sync.yml

name: repo-sync

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: timlevtt/github-sync@v2
      with:
        source_repo: "https://${{ secrets.PAT }}@github.com/timlevett/ytwatcher.git"
        source_branch: "master"
        destination_branch: "master"
        sync_tags: "true"
        github_token: ${{ secrets.PAT }}
